table Dim_Portales
	lineageTag: 3aa70af9-0494-459f-b0ab-274396c19812

	column ID_Portal
		dataType: int64
		formatString: 0
		lineageTag: 04e0b160-445e-4dac-a23b-0178f0fcd9b1
		summarizeBy: none
		sourceColumn: ID_Portal

		annotation SummarizationSetBy = Automatic

	column Nombre_Portal
		dataType: string
		lineageTag: ded71fb9-4fa5-4153-bdeb-dbddb879b4a6
		summarizeBy: none
		sourceColumn: Nombre_Portal

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a3dfd82b-6bc6-4b82-84cf-29d0f941a3bc
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Dim_Portales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Downloads\Gestion informacion\data\processed\modelo_estrella\Dim_Portales.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID_Portal", Int64.Type}, {"Nombre_Portal", type text}}),
				    #"Region Anadida" = Table.AddColumn(#"Tipo cambiado", "Region", each if [Nombre_Portal] = "Arbeitnow API" then "Externo" else "Panamá", type text)
				in
				    #"Region Anadida"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

